import image1 from './assets/static/per1.jpg'
export const imgArrData = [
    {
        'src':'https://picsum.photos/300/300',
        caption:'Nothing to say as of now',
        id:1,
    },
    {
        'src':'assets/static/per1.jpg',
        caption:'Caption 2',
        id:2,
    },
    {
        'src':image1,
        caption:'Caption 3',
        id:3,
    },
    {
        'src':'https://picsum.photos/700/300',
        caption:'Caption 4',
        id:4,
    },
    {
        'src':'https://picsum.photos/500/200',
        id:5,
    },{
        'src':'https://picsum.photos/500/400',
        caption:'Caption 4 cool minded meditation is always a best thing as it reduces stress',
        id:6,
    },
    {
        'src':'https://picsum.photos/500/500',
        id:7,
    },
    {
        'src':'https://picsum.photos/100/500',
        id:8,
    },
    {
        'src':'https://picsum.photos/200/500',
        id:9,
    },
    {
        'src':'https://picsum.photos/300/500',
        id:10,
    },
    {
        'src':'https://picsum.photos/200/300',
        id:11,
    },
    {
        'src':'https://picsum.photos/1200/2300',
        id:12,
    },
    {
        'src':'https://picsum.photos/400/500',
        id:13,
    },
    {
        'src':'https://picsum.photos/600/100',
        id:14,
    },
    {
        'src':'https://picsum.photos/600/200',
        id:15,
    },
    {
        'src':'https://picsum.photos/600/300',
        id:16,
    },
    {
        'src':'https://picsum.photos/600/400',
        id:17,
    },{
        'src':'https://picsum.photos/600/500',
        id:18,
    },
    {
        'src':'https://picsum.photos/600/600',
        id:19,
    },
    {
        'src':'https://picsum.photos/200/600',
        id:20,
    },
    {
        'src':'https://picsum.photos/300/600',
        id:21,
    },
    {
        'src':'https://picsum.photos/400/600',
        id:22,
    },
    {
        'src':'https://picsum.photos/200/300',
        id:23,
    },
    {
        'src':'https://picsum.photos/1200/2300',
        id:24,
    },
    {
        'src':'https://picsum.photos/1200/2300',
        id:25,
    },
];
